name: Bug Report
description: Create a bug report for this project.
title: "[BUG] Short but descriptive title"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### Bug Report Guidelines
        Thank you for taking the time to report a bug!
        Please fill out the sections below to help us understand the issue.
  - type: textarea
    id: description
    attributes:
      label: Description of the Bug
      description: |
        Briefly describe the bug you found.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version of the Software
      placeholder: Enter version number, commit hash with branch, or both.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce the Bug
      description: |
        Steps to reproduce the issue:
          1. Perform this action...;
          2. Perform that action...;
          3. ...;
          4. Observe the problem!
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Expected Behavior
      description: |
        A clear and concise description of what you expected.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Details
      description: |
        Provide any extra details, references, or links that might help us
        understand the problem (e.g., related issues, to-do notes, external
        documentation, etc.)
    validations:
      required: false
