blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/hypatiafsa/
    about: If you have a general question about the project, please use our
      discussions forum.
